// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5K5PThexAf9Y4WyqzwbUH5qr0fX9WvMc',
    appId: '1:902903571752:web:9272affa421ced50e95c1d',
    messagingSenderId: '902903571752',
    projectId: 'ultimatekmk-a3b41',
    authDomain: 'ultimatekmk-a3b41.firebaseapp.com',
    databaseURL: 'https://ultimatekmk-a3b41-default-rtdb.firebaseio.com',
    storageBucket: 'ultimatekmk-a3b41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6CFpRykqrqUOB_GaNKKjskg6JCvz2xtw',
    appId: '1:902903571752:android:f9f78c26ba6eb2eae95c1d',
    messagingSenderId: '902903571752',
    projectId: 'ultimatekmk-a3b41',
    databaseURL: 'https://ultimatekmk-a3b41-default-rtdb.firebaseio.com',
    storageBucket: 'ultimatekmk-a3b41.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyConxo1ooz8in86wLURpbG0Lt5o05F-PPQ',
    appId: '1:902903571752:ios:9e029f82682e5b75e95c1d',
    messagingSenderId: '902903571752',
    projectId: 'ultimatekmk-a3b41',
    databaseURL: 'https://ultimatekmk-a3b41-default-rtdb.firebaseio.com',
    storageBucket: 'ultimatekmk-a3b41.appspot.com',
    iosClientId: '902903571752-k5m5qclp67embk4ishkjqnid01t66qu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ultimatekmkfinal',
  );
}
